/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAfiliadosRouteImport } from './routes/admin-afiliados'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as BindsRouteImport } from './routes/binds'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as JogadoresRouteImport } from './routes/jogadores'
import { Route as MercadosRouteImport } from './routes/mercados'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as StakeRouteImport } from './routes/stake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/admin-afiliados',
  path: '/admin-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const BindsRoute = BindsRouteImport.update({
  id: '/binds',
  path: '/binds',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresRoute = JogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadosRoute = MercadosRouteImport.update({
  id: '/mercados',
  path: '/mercados',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-afiliados': typeof AdminAfiliadosRoute
  '/afiliados': typeof AfiliadosRoute
  '/assinatura': typeof AssinaturaRoute
  '/binds': typeof BindsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/favoritos': typeof FavoritosRoute
  '/historico': typeof HistoricoRoute
  '/jogadores': typeof JogadoresRoute
  '/mercados': typeof MercadosRoute
  '/presets': typeof PresetsRoute
  '/stake': typeof StakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-afiliados': typeof AdminAfiliadosRoute
  '/afiliados': typeof AfiliadosRoute
  '/assinatura': typeof AssinaturaRoute
  '/binds': typeof BindsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/favoritos': typeof FavoritosRoute
  '/historico': typeof HistoricoRoute
  '/jogadores': typeof JogadoresRoute
  '/mercados': typeof MercadosRoute
  '/presets': typeof PresetsRoute
  '/stake': typeof StakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-afiliados': typeof AdminAfiliadosRoute
  '/afiliados': typeof AfiliadosRoute
  '/assinatura': typeof AssinaturaRoute
  '/binds': typeof BindsRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/favoritos': typeof FavoritosRoute
  '/historico': typeof HistoricoRoute
  '/jogadores': typeof JogadoresRoute
  '/mercados': typeof MercadosRoute
  '/presets': typeof PresetsRoute
  '/stake': typeof StakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-afiliados'
    | '/afiliados'
    | '/assinatura'
    | '/binds'
    | '/configuracoes'
    | '/favoritos'
    | '/historico'
    | '/jogadores'
    | '/mercados'
    | '/presets'
    | '/stake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-afiliados'
    | '/afiliados'
    | '/assinatura'
    | '/binds'
    | '/configuracoes'
    | '/favoritos'
    | '/historico'
    | '/jogadores'
    | '/mercados'
    | '/presets'
    | '/stake'
  id:
    | '__root__'
    | '/'
    | '/admin-afiliados'
    | '/afiliados'
    | '/assinatura'
    | '/binds'
    | '/configuracoes'
    | '/favoritos'
    | '/historico'
    | '/jogadores'
    | '/mercados'
    | '/presets'
    | '/stake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AssinaturaRoute: typeof AssinaturaRoute
  BindsRoute: typeof BindsRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FavoritosRoute: typeof FavoritosRoute
  HistoricoRoute: typeof HistoricoRoute
  JogadoresRoute: typeof JogadoresRoute
  MercadosRoute: typeof MercadosRoute
  PresetsRoute: typeof PresetsRoute
  StakeRoute: typeof StakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-afiliados': {
      id: '/admin-afiliados'
      path: '/admin-afiliados'
      fullPath: '/admin-afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binds': {
      id: '/binds'
      path: '/binds'
      fullPath: '/binds'
      preLoaderRoute: typeof BindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores': {
      id: '/jogadores'
      path: '/jogadores'
      fullPath: '/jogadores'
      preLoaderRoute: typeof JogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercados': {
      id: '/mercados'
      path: '/mercados'
      fullPath: '/mercados'
      preLoaderRoute: typeof MercadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AfiliadosRoute: AfiliadosRoute,
  AssinaturaRoute: AssinaturaRoute,
  BindsRoute: BindsRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FavoritosRoute: FavoritosRoute,
  HistoricoRoute: HistoricoRoute,
  JogadoresRoute: JogadoresRoute,
  MercadosRoute: MercadosRoute,
  PresetsRoute: PresetsRoute,
  StakeRoute: StakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
